version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: jpa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /Users/surajbiradar/docker-volume-mount:/var/lib/postgresql/data
    ports:
      - "5432:5432"
